-- ============================================================
-- seeds.sql — Realistic dummy data for UI prototyping
-- ============================================================
-- Add INSERT statements here.
-- Run `flowmo db:seed` to insert this data into your local DB.
-- Your schema must already be set up via `flowmo db:setup`.
-- ============================================================

-- Example:
-- Note: 'user' is a reserved word — always quote the table name.
-- INSERT INTO "user" (id, name, email, username, is_active) VALUES
--   ('user-001', 'Izam B.',  'izam@example.com',  'izam@example.com',  1),
--   ('user-002', 'Ali A.',   'ali@example.com',   'ali@example.com',   1),
--   ('user-003', 'Muthu R.', 'muthu@example.com', 'muthu@example.com', 1),
--   ('user-004', 'Ah H.',    'ahh@example.com',   'ahk@example.com',   0);
